In [3]:
import pandas as pd
import requests
import gmaps
from config import gkey

resource_path = "../../Resources"
all_by_state_daily_path = f"{resource_path}/AllByState-Daily.csv"

In [4]:
all_by_state_daily_df = pd.read_csv(all_by_state_daily_path)
all_by_state_daily_df.head()

,Active,Confirmed,Date,Deaths,Fatality Rate,Recovered,State Name,State,Active Diff,Confirmed Diff,Deaths Diff,Recovered Diff,Lat,Lon,Land Area (mi2),Population,Population Density,Per Capita Income,Median Household Income
0,0,0,2020-03-10,0,0.0,0,Alaska,AK,0,0,0,0,61.3707,-152.4044,211300.81,734417.0,3.475694,35617.249121,51875.0
1,0,0,2020-03-11,0,0.0,0,Alaska,AK,0,0,0,0,61.3707,-152.4044,211300.81,734417.0,3.475694,35617.249121,51875.0
2,0,0,2020-03-12,0,0.0,0,Alaska,AK,0,0,0,0,61.3707,-152.4044,211300.81,734417.0,3.475694,35617.249121,51875.0
3,1,1,2020-03-13,0,0.0,0,Alaska,AK,1,1,0,0,61.3707,-152.4044,211300.81,734417.0,3.475694,35617.249121,51875.0
4,1,1,2020-03-15,0,0.0,0,Alaska,AK,0,0,0,0,61.3707,-152.4044,211300.81,734417.0,3.475694,35617.249121,51875.0

In [5]:
max_date_df = all_by_state_daily_df.sort_values("Date", ascending = False)
max_date_df.head()

,Active,Confirmed,Date,Deaths,Fatality Rate,Recovered,State Name,State,Active Diff,Confirmed Diff,Deaths Diff,Recovered Diff,Lat,Lon,Land Area (mi2),Population,Population Density,Per Capita Income,Median Household Income
3397,2866,2909,2020-07-23,43,0.0148,0,Montana,MT,96,97,1,0,46.9219,-110.4544,135639.85,1038180.0,7.653945,29784.234687,49833.0
3533,23502,23818,2020-07-23,316,0.0133,0,Nebraska,NE,327,332,5,0,41.1254,-98.2681,76243.49,1900182.0,24.922547,31121.371768,55236.0
3125,46617,48053,2020-07-23,1436,0.0299,0,Mississippi,MS,969,982,13,0,32.7416,-89.6787,45729.42,2962109.0,64.774690,23556.907406,38418.0
2989,47120,48721,2020-07-23,1601,0.0329,0,Minnesota,MN,751,760,9,0,45.6945,-93.9002,77477.43,5523621.0,71.293291,36262.683567,60000.0
2853,78036,84431,2020-07-23,6395,0.0757,0,Michigan,MI,694,701,7,0,43.3266,-84.5361,55526.86,9935027.0,178.922903,30369.333747,52203.0

In [37]:
grouped_state_name = max_date_df.groupby(["State Name"])
grouped_state_name

population_density = grouped_state_name["Population Density"].max()
population_density

lat = grouped_state_name["Lat"].max()
lat

lon = grouped_state_name["Lon"].max()
lon

deaths = grouped_state_name["Deaths"].max()
deaths

pop_density_df = pd.DataFrame({"Population Density": population_density,
                               "Deaths": deaths,
                               "Lat": lat,
                               "Lon": lon})
pop_density_vs_deaths = pop_density_df.sort_values("Population Density", ascending = False)
pop_density_vs_deaths

deaths_by_pop_density_df = pop_density_df.sort_values("Deaths", ascending = False)
deaths_by_pop_density_df

                Population Density  Deaths      Lat       Lon
State Name
New York                424.151807   32594  42.1657  -74.9481
New Jersey             1259.397075   15737  40.2989  -74.5210
Massachusetts           880.152360    8484  42.2302  -71.5301
California              403.176406    8201  36.1162 -119.6816
Illinois                233.446533    7560  40.3495  -88.9861
Pennsylvania            285.775169    7093  40.5908  -77.2098
Michigan                178.922903    6395  43.3266  -84.5361
Florida                 469.666909    5518  27.7663  -81.6868
Texas                   124.836045    4622  31.0545  -97.5635
Connecticut             739.092300    4410  41.5978  -72.7554
Louisiana               117.631765    3574  31.1695  -91.8678
Maryland                627.327655    3409  39.0639  -76.8021
Georgia                 188.012554    3361  33.0406  -83.6431
Ohio                    285.194024    3256  40.3888  -82.7649
Arizona                  77.370494    3063  33.7298 -111.4312
Indiana                 186.140266    2880  39.8494  -86.2583
Virginia                216.071160    2054  37.7693  -78.1700
Colorado                 56.807890    1786  39.0598 -105.3111
North Carolina          215.802450    1756  35.6301  -79.8064
Minnesota                71.293291    1601  45.6945  -93.9002
Washington              124.961694    1482  47.4009 -121.4905
Mississippi              64.774690    1436  32.7416  -89.6787
Alabama                  97.938940    1397  32.3182  -86.9023
South Carolina          164.505495    1334  33.8569  -80.9450
Missouri                 89.713449    1189  38.4561  -92.2884
Rhode Island           1027.895605    1001  41.6809  -71.5118
Tennessee               163.203018     925  35.7478  -86.6923
Wisconsin               107.723346     878  44.2685  -89.6165
Iowa                     55.898353     820  42.0115  -93.2105
Nevada                   63.315839     709  38.3135 -117.0554
Kentucky                115.411849     684  37.6681  -84.6701
New Mexico               23.671155     596  34.8405 -106.2485
Delaware                485.051173     529  39.3185  -75.5071
Oklahoma                 58.067478     477  35.5653  -96.9289
New Hampshire           147.962887     405  43.4525  -71.5639
Arkansas                 60.044061     386  34.9697  -92.3731
Kansas                   36.270928     322  38.5266  -96.7265
Nebraska                 24.922547     316  41.1254  -98.2681
Oregon                   66.804442     273  44.5720 -122.0709
Utah                     85.538458     267  40.1500 -111.8624
Idaho                    29.133027     138  44.2405 -114.4788
South Dakota             11.606300     121  44.2998  -99.4388
Maine                    54.950441     118  44.6939  -69.3819
West Virginia            80.192654     102  38.4912  -80.9545
North Dakota             11.256518      97  47.5289  -99.7840
Vermont                  67.127802      56  44.0459  -72.7107
Montana                   7.653945      43  46.9219 -110.4544
Hawaii                  261.403411      26  21.0943 -157.4983
Wyoming                   8.709935      25  42.7560 -107.3025
Alaska                    3.475694      19  61.3707 -152.4044

In [38]:
gmaps.configure(gkey)

In [39]:
# Store 'Lat' and 'Lng' into  locations 
locations = deaths_by_pop_density_df[["Lat", "Lon"]].astype(float)

# pop_density_df = pop_density_df.dropna()
population_densitys= deaths_by_pop_density_df["Population Density"].astype(float)

In [40]:
# Create a poverty Heatmap layer
fig = gmaps.figure()

heat_layer = gmaps.heatmap_layer(locations, weights= population_densitys, 
                                 dissipating=False, max_intensity= 0,
                                 point_radius = 1.0)

fig.add_layer(heat_layer)

fig

Figure(layout=FigureLayout(height='420px'))

In [41]:
# Convert deaths to list
deaths = deaths_by_pop_density_df["Deaths"].tolist()

In [43]:
death_layer = gmaps.symbol_layer(
    locations, fill_color='rgba(150, 0, 0, 0.4)',
    stroke_color='rgba(0, 150, 0, 0.4)', scale=2,
    info_box_content=[f"Death amount: {death}" for death in deaths]
)


fig = gmaps.figure()
fig.add_layer(death_layer)

fig

Figure(layout=FigureLayout(height='420px'))

In [44]:
# Create a combined map
fig = gmaps.figure()

fig.add_layer(heat_layer)
fig.add_layer(death_layer)

fig

Figure(layout=FigureLayout(height='420px'))